version: 0.2

phases:
  install:
    commands:
      - npm install
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs #aws code build use ubuntu environement
      - which nodejs
      - which node

  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - npm prune --production
    post_build:
      commands:
        - echo Build completed on `date`  
artifacts:

  files:
    - "**/*"
  discard-paths: no
  base-directory: dist  